name: Build and Push Docker Image

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 30720 # Reserve 30GB for build
          swap-size-mb: 4096 # Increase swap
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - name: Aggressive disk cleanup
        run: |
          echo "=== Initial disk usage ==="
          df -h

          # Remove unnecessary packages and caches
          sudo apt-get clean
          sudo apt-get autoclean
          sudo apt-get autoremove -y

          # Remove large directories not needed for Docker builds
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

          # Clear temp and cache directories
          sudo rm -rf /tmp/*
          sudo rm -rf /var/tmp/*
          sudo rm -rf /var/cache/apt/archives/*
          sudo rm -rf ~/.cache/*

          # Remove old logs
          sudo journalctl --vacuum-time=1d 2>/dev/null || true
          sudo find /var/log -type f -name "*.log" -delete 2>/dev/null || true

          echo "=== Disk usage after cleanup ==="
          df -h

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Configure Docker daemon for space optimization
        run: |
          # Configure Docker to use minimal space
          sudo mkdir -p /etc/docker
          echo '{
            "storage-driver": "overlay2",
            "max-concurrent-downloads": 3,
            "max-concurrent-uploads": 3
          }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: spruceemma/vibevoice-server:${{ github.ref_name }},spruceemma/vibevoice-server:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Optimize build
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          provenance: false # Reduce manifest size
          sbom: false # Disable SBOM generation to save space

      - name: Post-build cleanup
        if: always()
        run: |
          echo "=== Cleaning up Docker resources ==="
          docker system prune -af --volumes
          docker builder prune -af

          echo "=== Final disk usage ==="
          df -h
